sonar.projectKey=gabrielchv_omnistore
sonar.organization=gabrielchv
sonar.projectName=omnistore

sonar.sources=services/orders/src,services/payments/src,services/notifications/src
sonar.tests=services/orders/src,services/payments/src,services/notifications/src
sonar.test.inclusions=**/*.spec.ts
sonar.exclusions=strapi/**,**/node_modules/**,**/dist/**,**/build/**

sonar.javascript.lcov.reportPaths=
sonar.typescript.tsconfigPaths=services/orders/tsconfig.json,services/payments/tsconfig.json,services/notifications/tsconfig.json
